### ISSUE TITLE
Ability to specify custom paper size

### ISSUE THREAD

**Issue by jonahgeorge** [alfianlensundev/tauri-plugin-printer#5]
It appears that this library only supports hardcoded paper sizes. The Electron print API supports custom paper sizes via a `{ width: x, height: y }` param; however, do to shelling out to SumatraPDF there may be a limitation in implementing this.

Links:
- https://www.electronjs.org/de/docs/latest/api/web-contents#contentsprintoptions-callback (see `pageSize`)
- https://github.com/sumatrapdfreader/sumatrapdf/discussions/3173
- https://github.com/sumatrapdfreader/sumatrapdf/pull/1815/commits/2104e6104ea759dc4f839c7e8be5973f5a4f0488

**Comment by alfianlensundev** [comment]
@jonahgeorge Thank you for your input, I will add it in the next version
